
[window]
decorations="Transparent"
opacity=0.9
startup_mode="Maximized"
option_as_alt="Both"

# [shell]
# program="/usr/local/bin/tmux"
# args=["new-session", "-A", "-D", "-s", "main"]

[font]
normal={family="CommitMono", style="Regular"}
# normal={family="Hack Nerd Font Mono", style="Regular"}
# normal={family="Comic Mono", style="Regular"}
# normal={family="Berkeley Mono Trial", style="Regular"}
size=14

[colors.primary]
background = "#08080b"
foreground = "#787c99"

[colors.cursor]
# cursor = "#787c99"
cursor = "#f0d67c"

[colors.selection]
text = "CellForeground"
background = "#515c7e"

[colors.normal]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"

[colors.bright]
black = "#363b54"
red = "#f7768e"
green = "#41a6b5"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#787c99"
