
[window]
decorations="Transparent"
opacity=0.9
startup_mode="Maximized"
option_as_alt="Both"

# [shell]
# program="/usr/local/bin/tmux"
# args=["new-session", "-A", "-D", "-s", "main"]

[font]
normal={family="JetBrainsMono NF", style="Semibold"}
size=12

[cursor]
style="Underline"

[colors.primary]
background="0x222436"
foreground="0xc8d3f5"

[colors.normal]
black="0x1b1d2b"
red="0xff757f"
green="0xc3e88d"
yellow="0xffc777"
blue="0x82aaff"
magenta="0xc099ff"
cyan="0x86e1fc"
white="0x828bb8"

[colors]
indexed_colors=[{index=16, color="0xff966c"},{index=17, color="0xc53b53"},]


