return   {
    -- "williamboman/mason.nvim",
    --   cmd = { "Mason", "MasonInstall", "MasonInstallAll", "MasonUpdate" },
    -- opts = {
    --   ensure_installed = {
    --     "gopls",
    --     "typescript-language-server",
    --     "eslint-lsp",
    --     "prettier",
    --     "js-debug-adapter",
    --     "clangd",
    --     "rust-analyzer",
    --   "lua-language-server",
    --   },
    -- },
    --   config = function(_, opts)
    --   require("mason").setup(opts)
    --
    --   -- custom nvchad cmd to install all mason binaries listed
    --   vim.api.nvim_create_user_command("MasonInstallAll", function()
    --     vim.cmd("MasonInstall " .. table.concat(opts.ensure_installed, " "))
    --   end, {})
    --
    --   vim.g.mason_binaries_list = opts.ensure_installed
    --
    -- end,
  }
